config/routes.rb
Rails.application.routes.draw do


  resources :tasks do
    resources :task_images
  end
  devise_for :users
  root to: 'pages#home', as: 'home'

  get '/profile/:id', to: 'pages#profile', as: 'profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_images

  scope :latest, -> { order(created_at: :desc) }
end

app/models/task_image.rb
class TaskImage < ApplicationRecord
  belongs_to :task

  mount_uploader :image, TaskImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
  mount_uploader :image, AvatarImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :bio, :image])
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def profile
    @user = User.find(params[:id])
  end

end

app/controllers/task_images_controller.rb
class TaskImagesController < ApplicationController
  before_action :authenticate_user!

  def new
    @task_image = TaskImage.new
    @task = Task.find(params[:task_id])
  end

  def create
    @task_image = TaskImage.new(task_image_params)
    @task = Task.find(params[:task_id])
    @task_image.task = @task
    if @task_image.save
      flash[:notice] = ''
      redirect_to @task
    else
      render :new
    end

  end

  private
  def task_image_params
    params.require(:task_image).permit([:image, :caption])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    if @task.save
      flash['notice'] = 'تم الحفظ بنجاح'
      redirect_to task_path(@task)
    else
      render :new
    end
  end


  private
  def task_params
    params.require(:task).permit(:name, :description, :url, :company)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/task_images_helper.rb
module TaskImagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
  <div class="container">
    <a class="navbar-brand" href="#"> الترا بزنس </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">



        <% if user_signed_in? %>

        <div class="dropdown show">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.image.thumb.nil? %>
              <%= image_tag 'profile.jpg', width: 28, height: 28, class: 'rounded-circle' %>

            <% else %>

              <%= image_tag current_user.image.thumb.url, width: 28, height: 28, class: 'rounded-circle' %>
            <% end %>
            <%= "#{current_user.first_name} #{current_user.last_name}" %>
          </a>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <%= link_to 'البروفايل', profile_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'تسجيل خروج', destroy_user_session_path, class: 'dropdown-item', method: :delete %>

          </div>
        </div>



        <% else %>
        <li class="nav-item active">
          <%= link_to "تسجيل دخول", new_user_session_path, class: 'nav-link btn btn-success text-white ml-1' %>
        </li>
        <li class="nav-item active">
          <%= link_to "انشاء حساب", new_user_registration_path, class: 'nav-link btn btn-primary text-white' %>
        </li>

        <% end %>


      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="rtl">
  <head>
    <title>Cool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <% if not notice.nil? %>
      <div class="alert alert-success alert-dismissible fade show text-right" role="alert">
        <p>
          <%= notice %>
        </p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>

      <% if not alert.nil? %>
      <div class="alert alert-alert alert-dismissible fade show text-right" role="alert">
        <p>
          <%= alert %>
        </p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h4> welcome home </h4>

app/views/pages/profile.html.erb
<div class="row">

  <div class="col col-2">
    <% if @user.image.medium.nil? %>
      <%= image_tag 'profile.jpg', class: 'img-thumbnail' %>
    <% else %>
      <%= image_tag @user.image.medium.url, class: 'img-thumbnail' %>
    <% end %>
  </div>

  <div class="col col-10">
    <div class="jumbotron">
      <h4 class="text-right"> <%= "#{@user.first_name} #{@user.last_name}" %> </h4>
      <% if !@user.bio.nil? %>
        <p class="text-muted text-right">
          <%= @user.bio %>
        </p>
      <% else %>
        <p class="text-right">
          <b> no bio </b>
        </p>
      <% end %>
    </div>

    <%= render 'tasks/task_list', {tasks: @user.tasks.latest, user: @user}  %>
  </div>

</div>

app/views/task_images/_task_image_list.html.erb
<% images.each do |image| %>

  <%= image_tag image.image.medium.url, class: 'img-thumbnail ml-2' %>

<% end %>

app/views/task_images/new.html.erb
<div class="row">
  <div class="col text-right">
    <h4>اضافه صوره للعمل </h4>
    <%= form_with model: [@task, @task_image], local: true do |form| %>

      <div class="form-group">
        <%= form.label :image, 'الصوره*' %>
        <%= form.file_field :image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :caption, 'كابشن' %>
        <%= form.text_field :caption, class: 'form-control', placeholder: 'وصف الصوره .....' %>
      </div>

      <%= form.submit 'اضافه', class: 'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/tasks/_task_list.html.erb
<% if tasks.empty? %>
  <p class="text-muted font-weight-bold text-right">
    لا يوجد مشاريع بعد هنا .....
    <%= link_to 'اضافه مشروع', new_task_path %>
  </p>

<% else %>
  <% if user == current_user %>
  <p class="text-right">
    العدد الكلي <b> <%= user.tasks.count %> </b>

    &nbsp; &nbsp; &nbsp;
    <u>
    <%= link_to 'اضافه مشروع جديد من هنا', new_task_path %></u>
  </p>
  <hr>
  <% end %>


  <% tasks.each do |task| %>
    <div class="task">
      <p class="text-right">
        <%= link_to task.name, task_path(task) %>

      </p>
      <p class="lead text-right">
        <%= truncate(task.description, length: 50, omission: '...') %>
      </p>
    </div>
    <hr>
  <% end %>

<% end %>

app/views/tasks/new.html.erb
<h4 class="text-right"> انشاء عمل سابق </h4>

<div class="text-right">
  <%= form_with model: @task, local: true do |form| %>

    <div class="form-group">
      <%= form.label :name, 'الاسم*' %>
      <%= form.text_field :name, class: 'form-control', placeholder: 'اسم العمل ...' %>
    </div>

    <div class="form-group">
      <%= form.label :description, 'الوصف*' %>
      <%= form.text_area :description, class: 'form-control', placeholder: 'تفاصيل العمل ....' %>
    </div>

    <div class="form-group">
      <%= form.label :url, 'عنوان الموقع' %>
      <%= form.text_field :url, class: 'form-control', placeholder: 'عنوان الموقع ....' %>
      <small class="text-muted"> في حاله كان العمل موقع الكتروني او تطبيق للهاتف يمكنك اضافه لينك الموقع او لينك تحميل التطبيق </small>
    </div>

    <div class="form-group">
      <%= form.label :company, 'اسم الشركه' %>
      <%= form.text_field :company, class: 'form-control', placeholder: 'الشركه .....' %>
    </div>

    <%= form.submit 'انشاء..', class: 'btn btn-success' %>


  <% end %>
</div>

app/views/tasks/show.html.erb
<div class=" row ">
  <div class="col-7 text-right">
    <h4 class="text-info"> <%= @task.name %> </h4>

    <p>
      <%= @task.description %>
    </p>

    <% if @task.url.nil? %>
      <p>
        الموقع : لايوجد
      </p>
      <% else %>
      <p>
        الموقع: <%= link_to @task.url, @task.url, target: '_blank' %>
      </p>
    <% end %>

    <% if @task.company.nil? %>
      <p>
        الشركه: لايوجد
      </p>
    <% else %>
      <p class="text-success">
        الشركه : <b> <%= @task.company %> </b>
      </p>
    <% end %>
    <hr>
    <%= render 'task_images/task_image_list', images: @task.task_images %>
    <%= link_to 'اضافه صوره', new_task_task_image_path(@task), class: 'btn btn-outline-success' %>

    <hr>
    <% if @task.user.image.nil? %>
      <%= image_tag 'profile.jpg', width: 30, height: 30, class: 'rounded-circle' %>
      <%= link_to "#{@task.user.first_name} #{@task.user.last_name}", profile_path(@task.user) %>
    <% else %>

      <%= image_tag @task.user.image.thumb.url, width: 30, height: 30, class: 'border-circle' %>
    <% end %>



    <%= time_ago_in_words(@task.created_at) %> ago
  </div>
</div>